autenticar admin
TreinaDev/payment-fraud pull request #11
Opened 2021-03-26 01:11 UTC by juniorivn

Feature para autenticar usuário/admin no sistema de pagamentos e fraudes.
Será feita uma nova feature para gerenciar usuários/admins.

2021-03-26 13:53 UTC, joaorsalmeida commented on spec/features/admin_
> +
Esse arquivo parece incompleto (inclusive o nome). Vale a pena testar também o cadastro de pessoas sem o email correto, o que acham? Daí a funcionalidade fica 100%.

2021-03-26 13:54 UTC, joaorsalmeida requested changes
Pra deixar tudo 100% que tal já tratar o cadastro também? Vi que criaram um arquivo de teste pra isso mas ele ficou incompleto. Já vamos testar o cenário de usuários com email incorreto e aí fica tudo pronto.

2021-03-29 06:53 UTC, juniorivn commented
Incluso novos testes e a validação de cadastro com o domínio 'smartflix.com.br'

2021-03-29 06:56 UTC, juniorivn commented on spec/features/admin_
> +
Incluso novos testes e a validação de cadastro com o domínio 'smartflix.com.br'

2021-03-29 07:02 UTC, juniorivn commented
Incluso novos testes e a validação de cadastro com o domínio 'smartflix.com.br'

2021-03-29 21:57 UTC, juniorivn commented
Incluso novos testes e a validação de cadastro com o domínio 'smartflix.com.br'

2021-03-29 23:12 UTC, joaorsalmeida approved these changes
Faltou fazer testes para o `sign_up`. Vou aprovar para destravar mas lancem no backlog uma tarefa de validar o cadastro de novas pessoas na app por favor.

2021-03-29 23:42 UTC, merged