Refatorando atributos da API meios de pagamentos
TreinaDev/payment-fraud pull request #16
Opened 2021-04-01 20:38 UTC by chrisleo-usa

2021-04-02 17:29 UTC, joaorsalmeida commented on app/controllers/api/v1/payment_methods_controller.rb
> +          { icon: { include: { blob:
Seria importante garantir que o teste reflete essa mudança no json. Você pode ajustar isso antes de seguirmos?

2021-04-02 17:29 UTC, joaorsalmeida requested changes
Como temos uma mudança no `json` de retorno da API, seria importante atualizar o teste referente ao endpoint impactado.

2021-04-03 15:33 UTC, chrisleo-usa commented on app/controllers/api/v1/payment_methods_controller.rb
> +          { icon: { include: { blob:
Perfeito João, teste atualizado. 
Só achei que ele ficou muito gigante, tem alguma sugestão de melhoria?

2021-04-05 19:03 UTC, joaorsalmeida commented on app/controllers/api/v1/payment_methods_controller.rb
> +          { icon: { include: { blob:
Vou aprovar como ficou, mas entendi seu ponto. Talvez separar em 2 testes as questões de: testar uma coleção e testar a imagem. Talvez no teste de retorno da coleção não precisava ser testada a imagem e a imagem seria testada em outro cenário.

2021-04-05 19:03 UTC, joaorsalmeida approved these changes

2021-04-05 19:03 UTC, merged