Efetivar pagamento
TreinaDev/payment-fraud pull request #9
Opened 2021-03-24 22:13 UTC by chrisleo-usa

Esta feature altera o status de pagamento para aprovado ou recusado, efetivando pagamento. 

[Link do card resolvido](https://trello.com/c/3Pl1G4xb/20-efetivar-o-pagamento)

2021-03-24 23:14 UTC, joaorsalmeida commented on spec/requests/payment_management_spec.rb
> +      get "/api/v1/payments/#{payment.customer_token}"
Se esse é um teste de API vocês precisam garantir nas expectativas o que vai ser retornado para a app que fez a requisição.

2021-03-24 23:17 UTC, joaorsalmeida commented on app/models/payment.rb
> +    return false unless pending?
Esse código merece um teste unitário. O que acham?!

2021-03-24 23:17 UTC, joaorsalmeida requested changes
Pessoal, encontrei uns pontos que merecem ajustes.

2021-03-24 23:19 UTC, joaorsalmeida commented on app/controllers/api/v1/payments_controller.rb
> +        payment = Payment.find_by(customer_token: params[:id])
O pagamento tem um token próprio. E o mesmo cliente vai poder fazer vários pagamentos ao longo do tempo. Então o correto aqui seria encontrar o `payment` pelo seu próprio token e não pelo `customer_token`

2021-03-25 14:33 UTC, le-santos commented on app/controllers/api/v1/payments_controller.rb
> +        payment = Payment.find_by(payment_token: params[:id])
@chrisleo-usa, Lembro de vc comentar sobre essa alteração, ótimo que já trocou.  Tomo a liberdade de acrescentar duas coisas. 
- Para ficar mais claro na definição da API, talvez seja interessante trocar o param `:id` por `:token`
- Alteraria também a definição no arquivo routes.rb, dando um override no padrão que usa id

```Ruby
# No controller:
# GET /api/v1/payments/:token
      def show
        payment = Payment.find_by(customer_token: params[:token])

# em routes.rb
    resources :payments, only: %i[ show create update ], param: :token
```

2021-03-25 15:17 UTC, joaorsalmeida commented on app/controllers/api/v1/payments_controller.rb
> +        payment = Payment.find_by(payment_token: params[:id])
Concordo :)

2021-03-25 15:20 UTC, joaorsalmeida requested changes
Pessoal, fiquei na dúvida sobre receber o status na criação de um pagamento. 

Fora isso está ótimo! 👍

2021-03-25 15:20 UTC, joaorsalmeida commented on app/controllers/api/v1/payments_controller.rb
> +        params.require(:payment).permit(:payment_method_id, :cpf, :customer_token, :plan_id, :status)
Me soou estranho: vamos aceitar o status na criação de um pagamento? E se alguém burlar e criar um pagamento já pago?

2021-03-25 16:44 UTC, chrisleo-usa commented on app/controllers/api/v1/payments_controller.rb
> +        payment = Payment.find_by(payment_token: params[:id])
Perfeito Leandro! realmente não havia pensado nesta possibilidade. 
Chegando em casa já faço essa alteração.

2021-03-25 16:46 UTC, chrisleo-usa commented on app/controllers/api/v1/payments_controller.rb
> +        params.require(:payment).permit(:payment_method_id, :cpf, :customer_token, :plan_id, :status)
Humm bem pensado... No próximo commit já faço essa alteração.

2021-03-25 22:44 UTC, joaorsalmeida approved these changes

2021-03-25 22:45 UTC, merged